<?php

/**
 * @file
 *
 * Companion pricing settings — configuration for the built-in companion
 * line-item rule.
 *
 * Surfaced on the "Afform Order Pricing" admin page at
 * civicrm/admin/setting/afform_order_pricing. The page is registered via
 * xml/Menu/afform_order.xml (for an explicit title); the form widgets are
 * auto-generated by the setting-admin mixin from the metadata below.
 *
 * Pseudoconstant and validation callbacks live in
 * \Civi\AfformOrder\PricingSettings.
 */

use CRM_AfformOrder_ExtensionUtil as E;

return [
  'afform_order_pricing_driver_price_field_id' => [
    'name' => 'afform_order_pricing_driver_price_field_id',
    'type' => 'Integer',
    'is_domain' => 1,
    'is_contact' => 0,
    'title' => E::ts('Driver PriceField'),
    'description' => E::ts('The PriceField whose chosen PriceFieldValues trigger creation of a companion line item. Typically the membership type selector.'),
    'default' => NULL,
    'html_type' => 'select',
    'html_attributes' => [
      'class' => 'crm-select2',
      'placeholder' => E::ts('- select -'),
    ],
    'pseudoconstant' => [
      'callback' => '\Civi\AfformOrder\PricingSettings::getPriceFields',
    ],
    'settings_pages' => [
      'afform_order_pricing' => [
        'weight' => 10,
      ],
    ],
  ],
  'afform_order_pricing_companion_price_field_id' => [
    'name' => 'afform_order_pricing_companion_price_field_id',
    'type' => 'Integer',
    'is_domain' => 1,
    'is_contact' => 0,
    'title' => E::ts('Companion PriceField'),
    'description' => E::ts('The PriceField used to record the companion line item that accompanies a chosen driver PriceFieldValue. Expected to be a single-value PriceField; its PriceFieldValue.amount is treated as a placeholder — the line item\'s unit_price is overridden from the MembershipType custom field configured below.'),
    'default' => NULL,
    'html_type' => 'select',
    'html_attributes' => [
      'class' => 'crm-select2',
      'placeholder' => E::ts('- select -'),
    ],
    'pseudoconstant' => [
      'callback' => '\Civi\AfformOrder\PricingSettings::getPriceFields',
    ],
    'settings_pages' => [
      'afform_order_pricing' => [
        'weight' => 20,
      ],
    ],
  ],
  'afform_order_pricing_companion_unit_price_field' => [
    'name' => 'afform_order_pricing_companion_unit_price_field',
    'type' => 'String',
    'is_domain' => 1,
    'is_contact' => 0,
    'title' => E::ts('Companion Unit Price Source'),
    'description' => E::ts('The numeric custom field on MembershipType whose value provides the unit_price for the companion line item. Stored as the API path "<custom_group_name>.<custom_field_name>" (e.g., "TMPA_membership_types.POLDF"). The driver PriceFieldValue\'s membership_type_id determines which MembershipType row is read.'),
    'default' => NULL,
    'html_type' => 'select',
    'html_attributes' => [
      'class' => 'crm-select2',
      'placeholder' => E::ts('- select -'),
    ],
    'pseudoconstant' => [
      'callback' => '\Civi\AfformOrder\PricingSettings::getMembershipTypeNumericCustomFields',
    ],
    'settings_pages' => [
      'afform_order_pricing' => [
        'weight' => 30,
      ],
    ],
  ],
];
